### ISSUE TITLE
backend suggest api endpoint should provide basic suggestions

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#118]
As the user is typing a search term, provide a list of suggestions that begin with what the user is typing.

Must suggest items of all types that are ours:

- Family names
- Places
- Luminaries
- Images
- Persons
- Compendium
- Stories
- Video
- Music

It should provide up to 5 suggestions as "Starts with".
If there is an exact match, suggest the exact match.

Future-proofing (bonus points): Add support for 5 items as "Sounds like".

**Comment by OriHoch** [comment]
the backend should provide an api call which gets a (possibly partial) search term and returning a list of suggestions

the main thing to determine for this issue is where it gets the suggestions from

I think for this iteration we can take is based on whatever data we have in our Elasticsearch - which currently means all the BHP data. In the future when we move to Clearmash we will still need to have some of the data stored in Elasticsearch to use for autosuggest (for example, we will keep the list of places and list of family names in our local instance with some migration)

**Comment by nuritgazit** [comment]
@OriHoch Just make sure not to pull information from "databases" other than the ones mentioned by @TheGrandVizier above, cause there are things like "donors" etc. that we mustn't use.

**Comment by OriHoch** [comment]
merged + deployed to test

see release notes for details

**Comment by OriHoch** [comment]
@TheGrandVizier  - sorry, not ready for testing yet, need to run indexing for elasticsearch

**Comment by OriHoch** [comment]
now it's deployed

**Comment by OriHoch** [comment]
some examples on test:
* http://devapi.dbs.bh.org.il/v1/suggest/*/ho
* http://devapi.dbs.bh.org.il/v1/suggest/places/ho
