### ISSUE TITLE
Some trees display results belonging to other trees (missing persons)

### ISSUE THREAD

**Issue by TheGrandVizier** [Beit-Hatfutsot/dbs-back#52]
Some persons are missing from some trees.
I cannot yet find a common denominator for these trees, but this does occur in some of the trees i sampled.
I will keep adding examples of this problem to this issue in the hopes that we see some sort of a pattern eventually.

Tree 12186 has 920 persons in BHP. Site displays 559.
Tree 12187 has 388 persons in BHP. Site displays 68.
Tree 12189 has 712 persons in BHP. Site displays 210.

The problem seem to be prevalent in fairly NEW trees.
There is also a peculiar coincidence:
Tree 12184 has 559 persons in BHP. Site displays 559.
Tree 12185 has 210 persons in BHP. Site displays NO RESULTS FOUND.

My current speculation is that 12185 was somehow missed in migration, which lead to a mis-match in unique identifiers in any trees that followed it.

**Comment by daonb** [comment]
Looks like it's related to the two processes Haim has for uploading trees and the two fields we have on each tree: `GenTreeFileId` and `GenTreePath` that contain the file name. Sometimes the we should use the file pointed to by the first field and sometimes by the second. I changed the code so that if there are two files, it will pick the newer file, but that didn't solve the problem either. When I look at the files for tree 12186:
```
-rwxr-xr-x 1 root root 390344 Nov 14 09:55 687d4ab7-072f-4ed3-ae4d-7d6e4a7055b3.ged*
-rwxr-xr-x 1 root root  63249 Nov 16 10:22 cf7131e0-430f-4dfa-89ef-789e165784b0.ged*
```
The bigger file is the older file. I don't know what's going on here. possibly black magic and voodoo.

**Comment by TheGrandVizier** [comment]
12185 Has now been migrated and matches the BHP result.

**Comment by TheGrandVizier** [comment]
Searching 12189 displays the content of tree 12185 (210 individuals).
Searching 12189 in BHP displays a tree with 712 individuals.

**Comment by nuritgazit** [comment]
Bug in BH, Doron Bali is on it

**Comment by TheGrandVizier** [comment]
@daonb Can we get a situation report on this?
Should everything be working now?
Any point it testing yet?

**Comment by nuritgazit** [comment]
@daonb ?

**Comment by daonb** [comment]
The solution for this is to run the migration with the complete gedcom path, using the `-g` option of the migrate script.

**Comment by TheGrandVizier** [comment]
@OriHoch 
Please approve

**Comment by OriHoch** [comment]
@TheGrandVizier - approve what?
